[package]
name = "playground-neon"
version = "1.0.0"
authors = ["Yoshua Wuyts <i@yoshuawuyts.com>"]
license = "MIT"

[lib]
name = "playground_neon"
crate-type = ["dylib"]

[dependencies]
neon = "0.1"
